[package]
name = "Needleman_Wunsch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clam = { git = "https://github.com/URI-ABD/clam.git", branch = "rust" }
